# -*- coding: utf-8 -*-
"""Capstone Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1siKps1IwNAql9dvqf1-pJj_5zHipzrhc
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt
!pip install catboost

dataframe = pd.read_csv(r"/content/Train_Data.csv", sep=",", encoding="unicode_escape")

dataframe.head()

dataframe.tail()

dataframe.shape

dataframe.columns

dataframe.dtypes

dataframe.describe

dataframe.nunique

#dataframe = dataframe.drop('pc', axis=1)
#sns.pairplot(dataframe)
dataframe.columns
dataframe.dtypes

test_data = pd.read_csv(r"/content/Test_Data.csv", sep=",", encoding="unicode_escape")

test_data.shape

test_data.columns

test_data.dtypes

dataframe.columns

from sklearn.impute import SimpleImputer
import xgboost as xgb
X_train_imputed = imputer.transform(X_train)
y_train_filled = y_train.fillna(0)

X_train.columns

y_train.shape

dataframe.columns

dataframe.dtypes

test_data.shape

from sklearn.impute import SimpleImputer
import xgboost as xgb
imputer = SimpleImputer(strategy='mean')
xgb_model = xgb.XGBClassifier(n_estimators=15, max_depth=4)
xgb_model.fit(X_train_imputed, y_train_filled)

test_data.columns

test_data.dtypes

test_data = test_data.drop(["index", "pc", "ma"], axis=1)
imputer = SimpleImputer(strategy='mean')
imputer.fit(test_data)
test_data_imputed = imputer.transform(test_data)
test_data_columns = test_data.columns
test_data_imputed_df = pd.DataFrame(test_data_imputed, columns=test_data_columns)
test_data_imputed_df.columns

test_data.shape

from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
imputer.fit(X_train)
test_data_imputed = imputer.transform(test_data)
rf_model = RandomForestClassifier(n_estimators=15, max_depth=4)
rf_model.fit(X_train_imputed, y_train_filled)
y_pred = rf_model.predict(test_data_imputed)

print(y_pred)

import pandas as pd
y_pred_df = pd.DataFrame(y_pred, columns=['pred'])
y_pred_df.to_csv('Capstone4.csv', index=False)